[[SQLite]]
arch = "aarch64"
git-tree-sha1 = "59f1179e203e11ab253db5ce39349775b855902b"
os = "macos"

    [[SQLite.download]]
    sha256 = "09c822e7339b65dc88af8b14ffb32c678ab91a346027c6f72d80000c579e5f6e"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.aarch64-apple-darwin.tar.gz"
[[SQLite]]
arch = "aarch64"
git-tree-sha1 = "326fd7cec3f70b1d64e248dff0aea3952e4e315f"
libc = "glibc"
os = "linux"

    [[SQLite.download]]
    sha256 = "b96111d4e383756471cd08d696c7b74d6f3eff81b2b21931dc70fd6179160d1e"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.aarch64-linux-gnu.tar.gz"
[[SQLite]]
arch = "aarch64"
git-tree-sha1 = "52f59ffe0307749454b24cc3d2cfcc4689469677"
libc = "musl"
os = "linux"

    [[SQLite.download]]
    sha256 = "1d248dbaef20a8197cc061b9b76db919f09f72aa023b1475a6d77c3b3aa00f59"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.aarch64-linux-musl.tar.gz"
[[SQLite]]
arch = "aarch64"
git-tree-sha1 = "1b537ed68bcd74238da41c58e96511562c424d69"
os = "freebsd"

    [[SQLite.download]]
    sha256 = "bdfd255cd0afa57e5b037d7e79eb393a9763464b622a89493f045b001e19d464"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.aarch64-unknown-freebsd.tar.gz"
[[SQLite]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8c413e524665d37c2b16d58bdcb7f77a17fb6abd"
libc = "glibc"
os = "linux"

    [[SQLite.download]]
    sha256 = "af09cfa0149e1eb780e119e76df2e390a2e7da71827f656e51f20f48cdc02d17"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.armv6l-linux-gnueabihf.tar.gz"
[[SQLite]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "caa66b3b20cd036287ddffc09d98e0e04dabe4c8"
libc = "musl"
os = "linux"

    [[SQLite.download]]
    sha256 = "fa1b0a7a9d494863c4e97c174de42de1e4ec62657bbbd1c52e9e861e06160cf9"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.armv6l-linux-musleabihf.tar.gz"
[[SQLite]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e7e441443091c21dcf714118d8c197a3d73c4cab"
libc = "glibc"
os = "linux"

    [[SQLite.download]]
    sha256 = "aa07cf7539e314568121ef462ddfbcce4d2e3590052c6d858440d0b209aed726"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.armv7l-linux-gnueabihf.tar.gz"
[[SQLite]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "90908c0843283b4fe507359970bc910a02635d07"
libc = "musl"
os = "linux"

    [[SQLite.download]]
    sha256 = "72dee827ba6f56d5fa6ca918967e31ab4d3a657fa7f72a97ab26b4fa8a2eb608"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.armv7l-linux-musleabihf.tar.gz"
[[SQLite]]
arch = "i686"
git-tree-sha1 = "c31070994d173739b6a14dd33b38433262f11853"
libc = "glibc"
os = "linux"

    [[SQLite.download]]
    sha256 = "9ed4ce66a7f1521a5f6aaa301544e9dfd0d52dd8f3e1ec1eb8a7ff11e35d36ed"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.i686-linux-gnu.tar.gz"
[[SQLite]]
arch = "i686"
git-tree-sha1 = "05017d3db86025d7cabd0b28f5d69da040a44ebf"
libc = "musl"
os = "linux"

    [[SQLite.download]]
    sha256 = "1d72c0b974fc95b386555b350fd593ca26d089f51b2fa501aaca154c90c85650"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.i686-linux-musl.tar.gz"
[[SQLite]]
arch = "i686"
git-tree-sha1 = "97dd59c1c17693fb872896edd891fe526d42ad2f"
os = "windows"

    [[SQLite.download]]
    sha256 = "16f8496c34c24c246b413f88ae9d929e3ffcfac5187c325c5885cab04d5503dc"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.i686-w64-mingw32.tar.gz"
[[SQLite]]
arch = "powerpc64le"
git-tree-sha1 = "e1b93c84c7bee1620a81a4135d3beec3e7d548af"
libc = "glibc"
os = "linux"

    [[SQLite.download]]
    sha256 = "b10e12cd5a782630e44f6f7b8183b7f168979ef1d968bbb0d649ba6c3a357350"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.powerpc64le-linux-gnu.tar.gz"
[[SQLite]]
arch = "riscv64"
git-tree-sha1 = "bce1c26353143b3b4a37355deff232928c1aacd2"
libc = "glibc"
os = "linux"

    [[SQLite.download]]
    sha256 = "b53ac5528e603812ac9753ff0f89cf9d9b501b9895421a8ea9e3f7ea88f7c361"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.riscv64-linux-gnu.tar.gz"
[[SQLite]]
arch = "x86_64"
git-tree-sha1 = "10ffabdedb097d73ae421d48ae96dd9646bae8a9"
os = "macos"

    [[SQLite.download]]
    sha256 = "f34e4eac564c025e9997333d08c1c0a3135bcb2150ca20b24b3dcbf434d3e14b"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.x86_64-apple-darwin.tar.gz"
[[SQLite]]
arch = "x86_64"
git-tree-sha1 = "b43a567606784a0d3fc06291c67f4ec5243791e6"
libc = "glibc"
os = "linux"

    [[SQLite.download]]
    sha256 = "7460c69ca424f84eedbc7ef980adead7cb57a1765c839eb3453e251f8961f37b"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.x86_64-linux-gnu.tar.gz"
[[SQLite]]
arch = "x86_64"
git-tree-sha1 = "b3303bd9a9b44be1920b6b86ac11a408ee950fda"
libc = "musl"
os = "linux"

    [[SQLite.download]]
    sha256 = "190733713b82ac84ee2d42720ad5dd18d5d9bc725f43d0523a71e3cc6688a3d1"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.x86_64-linux-musl.tar.gz"
[[SQLite]]
arch = "x86_64"
git-tree-sha1 = "20c6878fcd040800407ce7c8747bcb2c118e785f"
os = "freebsd"

    [[SQLite.download]]
    sha256 = "7154cd89568242f15a451b0556cd2e4af6a48649de5f0ca2658cfcd0304c771f"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.x86_64-unknown-freebsd.tar.gz"
[[SQLite]]
arch = "x86_64"
git-tree-sha1 = "0d6b599f2807be5eaf87d0776818f70db8adfa99"
os = "windows"

    [[SQLite.download]]
    sha256 = "0cf90a3461b9b4208b8a01f1afa1402a7deeea151934740c507254139c0634da"
    url = "https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/download/SQLite-v3.53.2+0/SQLite.v3.53.2.x86_64-w64-mingw32.tar.gz"
