# Autogenerated wrapper script for SQLite_jll for powerpc64le-linux-gnu
export libsqlite

using Zlib_jll
JLLWrappers.@generate_wrapper_header("SQLite")
JLLWrappers.@declare_library_product(libsqlite, "libsqlite3.so.0")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libsqlite,
        "lib/libsqlite3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
